language: java
jdk:
- oraclejdk8
cache:
  directories:
  - "$HOME/.m2"
  - "$HOME/.gradle"
deploy:
  provider: heroku
  app: appopup
  api_key:
    secure: iiIEyzzZfYV3syu9l6iVqmcd8AKmea+f3kLt+Nd2ejn+CLnzOLjw4xANLm3NKLLYBZxVH+cZnYppsAVEeDEodDHYy1iu6T7FeJpUDWb8W5QCUi9SjVu4eeTK1mn7v2cUy3Q/JDtZsJWXUYLT4TcIAtXiGXNCdMGzqqfAl4xxhcoSO8T1og220SiFn2Kaiq9mbUM9+OJh7fc8MEgwKCSTwprzNYwAyjauGR38nYw+Xe8Q3feMRNO3Fv3kXuQlsllev5nkDiqXySMwDYcjqvVekPwio3gxcCntStqyv2BU0KFzkiikoTauhqXANawGOu3QnSDmPjntGzhRqz5tFriypMmZmtTKYSyr59dWcuDSDK0C6yrSKBj0JbRcVjQ4svnPViVKus+pPcBMSp8fNtMfUYb1VnNu+bfx2VGanRX3DqgRo8aqog578CZWN+Bwl+FyaUSLeHWpFoln+vhhG0wlsyuYsqcjHf52k/i9zOx7hgkRSf4Kt8LbDLV8Qostlv6PHuf1bNt7RxXmmfpGFbCpcTp2KgBEVv/EzQ7BBQK/9LPHZB1RBr2vx3XulP4YvRmHfp8xP61fYVVvdXd6ZSFZKLgrm9msJnJkgITfBEPUUcK/AEpl/9h0RS39djEW+hndjTZwcxT3ofx3u669HrXq00S/7Ero9ZzdOIasum9V67s=
